name: MI Builder

on: [push]

jobs:
  packer-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packer
    steps:
      - name: Checkout the Source Code
        uses: "actions/checkout@v3"

      - name: Authentication with GCP

        uses: "google-github-actions/auth@v1"
        with: 
          credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest"

      - name: Archive the application
        working-directory: app
        run : tar -zcf /temp/app.tar.gz -X $GITHUB_WORKSPACE/app/exclude_files.txt $GITHUB_WORKSPACE/app

      - name: Init Packer
        id: init
        run: "packer init $GITHUB_WORKSPACE/packer/."

      - name: Validate Packer files
        id: validate
        run: "packer validate -var \"project_id=${{ secrets.PROJECT_ID }}\" $GITHUB_WORKSPACE/packer/. "

      - name: Build Machine Image
        id: build
        run: "packer build -var \"project_id=${{ secrets.PROJECT_ID }}\" $GITHUB_WORKSPACE/packer/. "
