name: Node.js CI

on: [pull_request, push]

jobs:
  server-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: test_db
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_ROOT_PASSWORD: rootpassword
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create env file
        run: |
          touch .env
          echo TEST_DB_NAME=test_db >> .env
          echo TEST_DB_USER=${{ secrets.MYSQL_USER }}>> .env
          echo TEST_DB_PASS=${{ secrets.MYSQL_PASSWORD }} >> .env
          
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.x'

      - name: Run npm Install
        run: npm ci

      - name: Install Test Dependencies
        run: npm i -g -D jest supertest

      - name: Run api test 
        run: npm test
