name: Node.js CI

on: [pull_request]

jobs:
  server-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Start MySQL
        run: sudo systemctl start mysql.service

      - name: Create env file
        run: |
          touch .env
          echo TEST_DB_NAME=test_db >> .env
          echo TEST_DB_USER=${{ secrets.MYSQL_USER }}>> .env
          echo TEST_DB_PASS=${{ secrets.MYSQL_PASSWORD }} >> .env
          
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.x'
          cache: npm

      - name: Run npm Install
        run: npm ci

      - name: Install Test Dependencies
        run: npm i -g -D jest supertest

      - name: Run api test 
        run: npm test
