name: API Tests

on:
  pull_request:
    branches: [main]

jobs:
  server-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Start MySQL and Configure Database
        run: |
          sudo systemctl start mysql
          sudo mysql -u root <<EOF
          CREATE DATABASE IF NOT EXISTS test_db;
          CREATE USER IF NOT EXISTS '${{ secrets.MYSQL_TEST_USER }}'@'localhost' IDENTIFIED BY '${{ secrets.MYSQL_TEST_PASSWORD }}';
          GRANT ALL PRIVILEGES ON test_db.* TO '${{ secrets.MYSQL_TEST_USER }}'@'localhost';
          FLUSH PRIVILEGES;
          EOF

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Create env file
        run: |
          touch .env
          echo TEST_DB_NAME=test_db >> .env
          echo TEST_DB_USER=${{ secrets.MYSQL_TEST_USER }} >> .env
          echo TEST_DB_PASS=${{ secrets.MYSQL_TEST_PASSWORD }} >> .env
          echo TEST_DB_HOST=localhost >> .env
          
      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
