
name: Packer Validation

on:
  pull_request:
    branches: [main]

jobs: 
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packer
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: latest

      - name: HCL Format Check
        run: packer fmt -check -diff $GITHUB_WORKSPACE/packer/.

      - name: Initialize Packer
        run: packer init $GITHUB_WORKSPACE/packer/.
        
      - name: Validate Packer Configuration
        run: |
          packer validate \
            -var "project_id=${{ secrets.PROJECT_ID }}" \
            -var "image_family=${{ vars.IMAGE_FAMILY }}" \
            -var "image_name=${{ vars.IMAGE_NAME }}" \
            $GITHUB_WORKSPACE/packer/.
