
name: Packer Validate

on: [pull_request]

jobs: 
  fmt-check:
    runs-on: ubuntu-latest
    name: Check formatting of packer files
    defaults:
      run:
        working-directory: packer
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Packer fmt
        run: packer fmt -check $GITHUB_WORKSPACE/packer/.

  validate:
    runs-on: ubuntu-latest
    name: Validate Packer configuration
    defaults:
      run:
        working-directory: packer
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Packer Init
        run: packer init $GITHUB_WORKSPACE/packer/.
        
      - name: Run `packer validate`
        id: validate
        run: "packer validate -var \"project_id=${{ secrets.PROJECT_ID }}\" -var \"env_db_user=${{ secrets.DB_USER }}\" -var \"env_prod_db=${{ secrets.PROD_DB }}\" -var \"env_db_pass=${{ secrets.DB_PASS }}\" $GITHUB_WORKSPACE/packer/. "
